name: 'gugush'
on: 
  push:
    branches: 
      - main
jobs:
  build_and_push:
    runs-on: self-hosted
   # env:
   #   exit_code : 1
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
      - name: 'Run our images'
        run: |
          docker build -t anun .
          docker run -d -p 5050:5050 --name anun anun:latest 
          echo "{exit_code}={(`docker exec -i anun /bin/bash -c "echo $?"`)}" >> $GITHUB_ENV
          echo "${github.exit_code}"
          docker stop anun
          docker rm anun
# $exit_code = `docker exec -i anun /bin/bash -c "echo $?"` 
           
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arturgrigoryan1/lesson_task_12.05:latest

