name: 'gugush'
on: 
  push:
    branches: 
      - main
jobs:
  build_and_push:
    runs-on: self-hosted
    outputs:
      env: ${{ steps.env.outputs.number }}
        
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
      - name: 'Run our images'
        id: env
        run: |
          docker build -t anun .
          docker run -d -p 5050:5050 --name anun anun:latest   

          exit_code=`docker exec -i anun /bin/bash -c "echo $?"`
          echo "::add-mask::$exit_code"
          echo "number=$exit_code" >> "$GITHUB_OUTPUT"
          echo "${{ steps.env.outputs.number }}"
          docker stop anun
          docker rm anun
          
        # echo "{exit_code}={`docker exec -i anun /bin/bash -c "echo $?"`}" >> $GITHUB_ENV
        # echo "${{ steps.env.outputs.exit_code }}"
      
        # echo "`docker exec -i anun /bin/bash -c "echo $?"`"
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arturgrigoryan1/lesson_task_12.05:latest

